name : "java maven build"
description : "setup java"

inputs :
  java-version:
    description: "java version"
    required: true
    default: "24"

  runs:
    using: "composite"
    steps:
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ inputs.java-version }}

      - name: build with maven
        run: mvn clean install
        shell: bash